# Generated by Django 3.2.6 on 2021-09-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210914_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='mobile_number',
        ),
    ]
